snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: 'redis://%env(REDIS_PASSWORD)%@%env(REDIS_HOST)%'
            options:
                read_write_timeout: 0
